### ISSUE TITLE
Failed to identify the chip

### ISSUE THREAD

**Issue by idoodler** [n3rd4n1/ccdbg#1]
I want to use this tool to flash a CC1110 chip, but somehow I am not able to identify the chip.
Because 2 of the default GPIO pins were already in use I changed the pins. I already tested the pins with "/sys/class/gpio/" manually and they go high and low as expected, but they do not work with ccdbg. Am I required to use the pins defined by you?

Thanks!

**Comment by n3rd4n1** [comment]
Hi! Unfortunately, the ccdbg tool is only verified and enabled to work on CC2530, CC2531, CC2533, CC2540, and CC2541. I'd like to add support but I am busy with work now and I don't have a CC1110 chip to experiment with. If you like, you can contribute to the project. ccdbg.\* need to be modified. I can help if you have specific questions regarding the implementation.

For the RPi interface, definitions for RESET, DC, and DD in ccdbg-rpi.cpp should be changed as required. I think you did this already.

**Comment by idoodler** [comment]
A few days passed and I decided to use an Intel Edison instead of an Raspberry Pi. The application can be compiled without any issue which is great:)
To add support for the `CC1110` chip I added the `chip ID 0x01` to the `ccdbg.h enum`, I also added it to the chip array in `ccdbg.c` with a `flashPageSize` of `1`. The `ID` and the `flashPageSize` are from [here](http://www.ti.com/lit/ug/swra124/swra124.pdf)
But it still fails. I checked the `ccdbg_command()` function and noticed, that the `readByte()` always returns 0. I double checked the wiring and I can't find an issue.

Do you have an idea how to solve this issue?

**Comment by idoodler** [comment]
I think I figured it out. The Intel Edison GPIO pins operate with 1.8V, the CC110 chip breakout I am using operates with 3.3V. I need a level converter.
